# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Link otomatik alinir, Lutfen Degistirmeyiniz!', max_length=80, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('cateogory', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_cateogory', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(help_text='Bu Alan Bos Birakilamaz!')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='BlogResimleri/blog.png', upload_to='BlogResimleri/%Y/%m/%d')),
                ('video', models.FileField(blank=True, upload_to='Videos/%Y/%m/%d')),
                ('link', models.URLField(blank=True)),
                ('readingCounter', models.IntegerField(default=0, editable=False)),
            ],
        ),
    ]
