# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, help_text='Link otomatik alinir, Lutfen Degistirmeyiniz!', max_length=80, null=True),
        ),
    ]
