# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20180328_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cateogory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Link otomatik alinir, Lutfen Degistirmeyiniz!', max_length=80, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(default='BlogResimleri/blog.png', upload_to='BlogResimleri/%Y/%m/%d')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCateogory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Link otomatik alinir, Lutfen Degistirmeyiniz!', max_length=80, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(default='BlogResimleri/blog.png', upload_to='BlogResimleri/%Y/%m/%d')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('enable', models.BooleanField(default=True)),
                ('cateogory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Cateogory')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
